const mongoose = require("mongoose");

const exerciseSchema = new mongoose.Schema({
  name: { type: String, required: true, unique: true },
  thumbnail: { type: String, required: true },
  video: { type: String, required: true },
  instruction: { type: String, required: true },
  muscles: [{ type: mongoose.Schema.Types.ObjectId, ref: "Muscle" }],
  trainingType: [
    {
      type: String,
      required: true,
      enum: [
        "Strength",
        "Cardio",
        "Flexibility",
        "Balance",
        "Endurance",
        "Power",
        "Mobility",
        "Conditioning",
      ],
    },
  ],
  category: [
    {
      type: String,
      enum: [
        "Bodybuilding",
        "Powerlifting",
        "Weightlifting",
        "Calisthenics",
        "CrossFit",
        "Functional Training",
        "Circuit/HIIT",
        "Sports Performance",
        "Yoga/Pilates",
        "Rehabilitation/Preventive",
        "Warm-up/Cool-down",
        "Martial Arts",
        "General Fitness",
      ],
      required: true,
    },
  ],
  movement: [
    {
      type: String,
      required: true,
      enum: [
        "Push",
        "Pull",
        "Squat",
        "Hinge",
        "Lunge",
        "Carry",
        "Rotation",
        "Anti-Rotation",
        "Gait/Locomotion",
        "Jump/Plyometrics",
      ],
    },
  ],
  equipment: [
    {
      type: String,
      required: true,
      enum: [
        "Bodyweight",
        "Dumbbell",
        "Barbell",
        "Machine",
        "Kettlebell",
        "Cable",
        "Band",
        "EZ-Bar",
        "Medicine Ball",
        "Smith Machine",
        "Pull-Up Bar",
        "Rowing Machine",
        "Treadmill",
        "Stationary Bike",
        "Elliptical",
        "Jump Rope",
        "Battle Ropes",
        "Sled",
        "Plyo Box",
        "Ab Wheel",
        "Weight Vest",
        "Resistance Bands",
        "TRX",
        "Sandbag",
        "SkiErg",
        "Assault Bike",
        "Jump Box",
        "Slam Ball",
        "Other",
      ],
    },
  ],
  duration: { type: Number, required: false },
  caloriesBurned: { type: Number, required: false },
  repetitions: { type: Number, required: false },
  timePerSet: { type: Number, required: false },
  tags: [
    {
      type: String,
      enum: [
        "Fat Loss",
        "Muscle Gain",
        "Endurance",
        "Core Strength",
        "Powerlifting",
        "Athletic Training",
        "Strength",
        "Flexibility",
        "Rehab",
        "Mobility",
        "Explosiveness",
        "Grip Strength",
        "Isometric",
        "Plyometric",
        "Full Body",
        "Upper Body",
        "Lower Body",
        "Cardio",
        "Bodyweight Only",
        "Weightlifting",
      ],
    },
  ],
});

exerciseSchema.index({ name: "text", tags: "text" });

module.exports = mongoose.model("Exercise", exerciseSchema);
